title: KPOP IDOL 4대 엔터 얼굴상 테스트
email: mun_1201@naver.com
description: KPOP IDOL 4대 엔터 얼굴상 테스트
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://mbtichat.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mun01180
github_username:  moony01

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag