title: KPOP 얼굴상 테스트
email: mun_1201@naver.com
description: 내 얼굴은 어떤 케이팝 소속사 얼굴상일까?
disqus_shortname: KPOP 얼굴상 테스트
google_analytics: G-J7NNCSLXY2
# avatar_url: /static/img/ico.jpg
url: "https://moony01.com/kpopface/"
baseurl: "/kpopface" # the subpath of your site, e.g. /blog
twitter_username: mun01180
github_username:  moony01

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag